-- MySQL Script generated by MySQL Workbench
-- Sun Mar  2 15:10:09 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tv_tracker_app
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tv_tracker_app
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema tv_tracker_app
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tv_tracker_app
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tv_tracker_app` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `tv_tracker_app` ;

-- -----------------------------------------------------
-- Table `tv_tracker_app`.`filmInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tv_tracker_app`.`filmInfo` (
  `filmID` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `runTime` TIME NULL,
  `description` VARCHAR(250) NULL,
  `rating` VARCHAR(8) NULL,
  PRIMARY KEY (`filmID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tv_tracker_app`.`actorInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tv_tracker_app`.`actorInfo` (
  `actorID` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NULL,
  PRIMARY KEY (`actorID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tv_tracker_app`.`directorInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tv_tracker_app`.`directorInfo` (
  `directorID` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NULL,
  PRIMARY KEY (`directorID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tv_tracker_app`.`filmToActor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tv_tracker_app`.`filmToActor` (
  `filmInfo_filmID` INT NOT NULL,
  `actorInfo_actorID` INT NOT NULL,
  PRIMARY KEY (`filmInfo_filmID`, `actorInfo_actorID`),
  INDEX `fk_filmInfo_has_actorInfo_actorInfo1_idx` (`actorInfo_actorID` ASC) VISIBLE,
  INDEX `fk_filmInfo_has_actorInfo_filmInfo_idx` (`filmInfo_filmID` ASC) VISIBLE,
  CONSTRAINT `fk_filmInfo_has_actorInfo_filmInfo`
    FOREIGN KEY (`filmInfo_filmID`)
    REFERENCES `tv_tracker_app`.`filmInfo` (`filmID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_filmInfo_has_actorInfo_actorInfo1`
    FOREIGN KEY (`actorInfo_actorID`)
    REFERENCES `tv_tracker_app`.`actorInfo` (`actorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tv_tracker_app`.`filmToDirector`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tv_tracker_app`.`filmToDirector` (
  `filmInfo_filmID` INT NOT NULL,
  `directorInfo_directorID` INT NOT NULL,
  PRIMARY KEY (`filmInfo_filmID`, `directorInfo_directorID`),
  INDEX `fk_filmInfo_has_directorInfo_directorInfo1_idx` (`directorInfo_directorID` ASC) VISIBLE,
  INDEX `fk_filmInfo_has_directorInfo_filmInfo1_idx` (`filmInfo_filmID` ASC) VISIBLE,
  CONSTRAINT `fk_filmInfo_has_directorInfo_filmInfo1`
    FOREIGN KEY (`filmInfo_filmID`)
    REFERENCES `tv_tracker_app`.`filmInfo` (`filmID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_filmInfo_has_directorInfo_directorInfo1`
    FOREIGN KEY (`directorInfo_directorID`)
    REFERENCES `tv_tracker_app`.`directorInfo` (`directorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `tv_tracker_app` ;

-- -----------------------------------------------------
-- Table `tv_tracker_app`.`userinfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tv_tracker_app`.`userinfo` (
  `userID` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(30) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `age` INT NULL DEFAULT NULL,
  PRIMARY KEY (`userID`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `userID_UNIQUE` (`userID` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tv_tracker_app`.`userToFilm`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tv_tracker_app`.`userToFilm` (
  `userinfo_userID` INT NOT NULL,
  `filmInfo_filmID` INT NOT NULL,
  PRIMARY KEY (`userinfo_userID`, `filmInfo_filmID`),
  INDEX `fk_userinfo_has_filmInfo_filmInfo1_idx` (`filmInfo_filmID` ASC) VISIBLE,
  INDEX `fk_userinfo_has_filmInfo_userinfo_idx` (`userinfo_userID` ASC) VISIBLE,
  CONSTRAINT `fk_userinfo_has_filmInfo_userinfo`
    FOREIGN KEY (`userinfo_userID`)
    REFERENCES `tv_tracker_app`.`userinfo` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_userinfo_has_filmInfo_filmInfo1`
    FOREIGN KEY (`filmInfo_filmID`)
    REFERENCES `tv_tracker_app`.`filmInfo` (`filmID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
